export const LENDER_TYPES = [
  { label: 'Alterna Bank', value: '1' },
  { label: 'Alterna Savings', value: '2' },
  { label: 'ATB Financial', value: '26' },
  { label: 'B2B Bank', value: '3' },
  { label: 'Bridgewater', value: '4' },
  { label: 'CMLS', value: '5' },
  { label: 'CMLS Adapt', value: '6' },
  { label: 'CMLS Attain', value: '7' },
  { label: 'CMLS Aveo', value: '8' },
  { label: 'First National', value: '10' },
  { label: 'Lendwise', value: '11' },
  { label: 'Manulife', value: '12' },
  { label: 'MCAN/XMC', value: '13' },
  { label: 'MCAP', value: '14' },
  { label: 'Merix', value: '15' },
  { label: 'Paradigm', value: '16' },
  { label: 'People’s Bank', value: '17' },
  { label: 'Private Lender', value: '18' },
  { label: 'RFA', value: '19' },
  { label: 'RMG', value: '20' },
  { label: 'TD Bank', value: '22' },
  { label: 'Verico LifeCycle', value: '23' },
  { label: 'Wealth One', value: '24' },
  { label: 'Westboro', value: '25' }
];
